import type { NextPage } from 'next'
import Head from 'next/head'
import { Layout } from '../components/layout/Layout';
import { Productos } from '../components/Productos';
import { LangContext } from '../context/LangContext';


const Home: NextPage = () => {
  
  return (
    <LangContext>
    <div>
      
      <Head>
        <title>Restaurante</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Layout>
        
        <Productos/>
        
      </Layout>
      
    </div>
    </LangContext>  
    
  )
}


export default Home
